apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrate-api-chart.fullname" . }}
  labels:
    {{- include "pyrate-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: externalclient
      protocol: TCP
      name: externalclient
    - port: {{ .Values.service.internalclient }}
      targetPort: internalclient
      protocol: TCP
      name: internalclient
  selector:
    {{- include "pyrate-api-chart.selectorLabels" . | nindent 4 }}
